name: 🐞 Bug
description: Report any errors and problems
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug!
  - type: textarea
    attributes:
      label: Description
      description: Please give a clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run '...'
        2. See error...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Version
      description: Output of `python southwest.py --version`
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here such as logs, Google Chrome version, Python version, etc.
