name: Lint + Format

on:
  push:
    branches:
      - master
      - develop
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/lint-format.yml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/lint-format.yml"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint with Ruff
        uses: astral-sh/ruff-action@v3
      - name: Format with Ruff
        run: ruff format --check
